apiVersion: v1 
kind: Pod 
metadata: 
  name: cluster-ip-demo 
  labels: # pod labels 
    app: nginx 
    demo: service
spec: 
  containers:
  - name: nginx 
    image: nginx 
    ports:
    - containerPort: 80 

--- 

apiVersion: v1 
kind: Service 
metadata: 
  name: cluster-ip-service 
spec: 
  selector: # selecting the Pod by using the same Pod labels 
    app: nginx 
    demo: service
  ports:
    - protocol: TCP
      port: 80 # service port 
      targetPort: 80 # container port  
