apiVersion: v1 
kind: ConfigMap
metadata:
  name: filebeat-config 
data:
  filebeat.yml: | 
    filebeat.modules:
    - module: nginx
      access:
        enabled: true
        var.paths: ["/var/log/nginx/access.log*"]
      error:
        enabled: true
        var.paths: ["/var/log/nginx/error.log*"]
    output.console:
      pretty: true
---
apiVersion: v1 
kind: Deployment 
metadata:
  name: emptydir 
spec: 
  replicas: 2 
  selector:
    matchLabels:
      app: nginx 
      demo: emptydir
  template:
    metadata:
    spec:
      containers:
      - name: nginx 
        image: nginx 
        labels:
          app: nginx 
          demo: emptydir
        volumeMounts:
        - name: nginx-logs # volume name 
          mountPath: /var/log/nginx # where do you want to attach in the pod 

      - name: filebeat  
        image: docker.elastic.co/beats/filebeat:8.12.0
        volumeMounts:
        - name: nginx-logs # volume name 
          mountPath: /var/log/nginx # where do you want to attach in the pod 
        
        - name: filebeat-config 
          mountPath: /usr/share/filebeat/filebeat.yml # where do you want to attach in the pod 
          subPath: filebeat.yml 

      volumes:
      - name: nginx-logs 
        emptyDir: {}
      - name: filebeat-config 
        configMap: # We are creating the volume from the configmap 
          name: filebeat-config
          items:
          - key: filebeat.yml
            path: filebeat.yml
