apiVersion: apps/v1 
kind: ReplicaSet 
metadata: 
  name: replicaset # Replicaset name 
  labels: 
    app: nginx-replicaset 
    tier: frontend 
spec: 
  replicas: 2 
  matchLabels: # replicaset labels 
    app: nginx-replicaset 
    tier: frontend 

  template: # Pod definition 
    metadata:
      name: replicaset-demo # Pod name
      labels:
        app: nginx-replicaset 
        tier: frontend 
    spec: 
      containers:
      - name: nginx # container name
        image: nginx 
        ports: 
        - containerPort: 80 

