apiVersion: v1 
kind: ReplicaSet 
metadata: 
  name: replicaset-demo 
  labels: 
    app: nginx-replicaset 
    tier: frontend 
spec: 
  replicas: 2 
  matchLabels: 
    app: nginx-replicaset 
    tier: frontend 

  template: # Pod definition 
    metadata:
      name: nginx 
      labels:
        app: nginx-replicaset 
        tier: frontend 
    spec: 
      containers:
      - name: nginx 
        image: nginx 
        ports: 
        - containerPort: 80 
        
