apiVersion: v1 
kind: Pod 
metadata: 
  name: labels-demo-pod
  labels:
    course: DevOps 
    trainer: PremSagar 
spec: 
  containers: 
  - name: nginx 
    image: nginx 
    ports:
    - containerPort: 80