apiVersion: v1 
kind: Pod 
metadata: 
  name: environment-demo
spec: 
  containers: 
  - name: nginx 
    image: nginx 
    ports:
    - containerPort: 80
    env: 
    - name: COURSE 
      value: AWS DevSecOps
    - name: TRAINER 
      value: Prem Sagar Eri
