apiVersion: v1 
kind: Pod 
metadata: 
  name: config-demo 
spec: 
  containers:
  - name: nginx 
    image: nginx 
    ports:
    - containerPort: 80 
    env: 
    - name: COURSE 
      valueFrom: 
        configMapKeyRef:
          name: devops-config 
          key: COURSE
    - name: TRAINER 
      valueFrom:
        configMapKeyRef: # We don't need to put - here because we are retrieving only a single key in devops-config 
          name: devops-config 
          key: TRAINER 

--- 
apiVersion: v1 
kind: Pod 
metadata: 
  name: config-demo-1
spec: 
  containers:
  - name: nginx 
    image: nginx 
    ports:
    - containerPort: 80 
    envFrom: 
    - configMapRef: # We need to put - because the devops-config has multiple key-value pairs
        name: devops-config 
        